<template>
  <v-container id="dashboard" fluid tag="section">
    <!-- <date-filter :init-date="initDate" @dateChange="onDateChange" /> -->

    <v-row v-if="stats" class="mr-2">
       <v-col cols="12">
        <base-material-card color="warning" style="background-color: #f7f7f7">
          <template v-slot:heading>
            <div class="text-h3 font-weight-light">Financial Stats</div>
          </template>
          <v-btn
              color="blue darken-1"
              text
              @click="toggleChart"
            >
              change Chart
            </v-btn>
           <vue-apex-charts
            width="100%"
            height="350"
            type="line"
            :options="requestsChart.options"
            :series="requestsChart.series"
          />
          <v-row>
           
           <v-col cols="3" >
              <v-card
                class="rounded-tl rounded-tr rounded-bl rounded-br elevation-1"
                color="white"
                flat
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      £
                      {{ stats.career_path_account_info.total_unprocessed_new }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text text-p">Total Unprocessed </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total amount of income generated by bookings which are not completed yet. Once booking is completed this amount will contribute to total revenue. </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>

            <v-col cols="3">
              <v-card
                class="rounded-tl rounded-tr rounded-bl rounded-br elevation-1"
                color="white"
                flat
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      £
                      {{ stats.career_path_account_info.total_revenue_new}}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text text-p">Total Revenue </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total amount of income (including Professional payment and CP fees) generated by bookings which are completed. </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>

            <v-col cols="3">
              <v-card
                class="rounded-tl rounded-tr rounded-bl rounded-br elevation-1"
                color="white"
                flat
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      £
                      {{ stats.career_path_account_info.total_discount_new}}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text text-p">Total Discount </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total amount of discounts provided against some offers or using discount codes. </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>

            <v-col cols="3">
              <v-card
                class="rounded-tl rounded-tr rounded-bl rounded-br elevation-1"
                color="white"
                flat
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      £
                      {{
                        toFixedTrunc(
                          (stats.career_path_account_info.total_commission_new),
                          2
                        )
                      }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text text-p">CareerPaths Commission </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total fee received by CP against the completed bookings </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>
            <v-col cols="2.4">
              <v-card
                class="rounded-tl rounded-tr rounded-bl rounded-br elevation-1"
                color="white"
                flat
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      £
                      {{
                        toFixedTrunc(
                          (stats.career_path_account_info.total_professional_commission_new),
                          2
                        )
                      }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text text-p">Mentors Commission </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total fee received by mentors against the completed bookings </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>
             <v-col cols="2.4">
              <v-card
                class="rounded-tl rounded-tr rounded-bl rounded-br elevation-1"
                color="white"
                flat
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      £
                      {{ stats.career_path_account_info.total_charity }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text text-p">Total Charity </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total amount of charity generated by bookings which are completed. </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>

            <v-col cols="2.4" >
              <v-card
                class="rounded-tl rounded-tr rounded-bl rounded-br elevation-1"
                color="white"
                flat
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      £
                      {{
                        toFixedTrunc(
                          stats.career_path_account_info.total_payouts_new,
                          2
                        )
                      }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text text-p">Total Payouts </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total amount that is paid to the professionals plus any funds withdrawn by the professionals </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>
             <v-col cols="2.4" >
              <v-card
                class="rounded-tl rounded-tr rounded-bl rounded-br elevation-1"
                color="white"
                flat
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      £
                      {{ stats.career_path_account_info.total_refund_new }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text text-p">Total Refunded </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total amount of income refunded by CP for the bookings which are not completed/expire. </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>

            <v-col cols="2.4" >
              <v-card
                class="rounded-tl rounded-tr rounded-bl rounded-br elevation-1"
                color="white"
                flat
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      £
                      {{ stats.career_path_account_info.total_session_fee_new || 0}}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text text-p">Total Booking Fee </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total booking fee paid by customer</span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>
          </v-row>
          <v-row>
            <v-col cols="2">
              <v-card
                class="rounded-tl rounded-tr rounded-bl rounded-br elevation-1"
                color="white"
                flat
                @click="goToRetainCustomers(0)" 
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      {{ retain0 }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text text-p">Retained user>0 </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total amount of customers who completed more than 0 bookings. </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>
            <v-col cols="2">
              <v-card
                class="rounded-tl rounded-tr rounded-bl rounded-br elevation-1"
                color="white"
                flat
                @click="goToRetainCustomers(1)"
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      {{ retain1 }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text text-p">Retained user>1 </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total amount of customers who completed more than 1 bookings. </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>
            <v-col cols="2">
              <v-card
                class="rounded-tl rounded-tr rounded-bl rounded-br elevation-1"
                color="white"
                flat
                @click="goToRetainCustomers(2)"
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      {{ retain2 }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text text-p">Retained user>2 </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total amount of customers who completed more than 2 bookings. </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>
            <v-col cols="2">
              <v-card
                class="rounded-tl rounded-tr rounded-bl rounded-br elevation-1"
                color="white"
                flat
                @click="goToRetainCustomers(3)"
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      {{ retain3 }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text text-p">Retained user>3 </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total amount of customers who completed more than 3 bookings. </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>
            <v-col cols="2">
              <v-card
                class="rounded-tl rounded-tr rounded-bl rounded-br elevation-1"
                color="white"
                flat
                @click="goToRetainCustomers(4)"
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      {{ retain4 }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text text-p">Retained user>4 </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total amount of customers who completed more than 4 bookings. </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>
            <v-col cols="2">
              <v-card
                class="rounded-tl rounded-tr rounded-bl rounded-br elevation-1"
                color="white"
                flat
                @click="goToRetainCustomers(5)"
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      {{ retain5 }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text text-p">Retained user>5 </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total amount of customers who completed more than 5 bookings. </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>
          </v-row>
        </base-material-card>
      </v-col>
       <v-col cols="6">
        <base-material-card style="background-color: #f7f7f7">
          <template v-slot:heading>
            <div class="text-h3 font-weight-light">User Stats</div>
          </template>
           <vue-apex-charts
            width="100%"
            height="350"
            type="line"
            :options="usersChart.options"
            :series="usersChart.series"
          />
          <v-row>
            <v-col cols="6">
              <v-card
                class="rounded-tl rounded-tr rounded-bl rounded-br elevation-1"
                color="white"
                flat
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      {{ stats.users_count.new_customers_count }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text">New Customers </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total number of customers that have joined between the dates selected above </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>

            <v-col cols="6">
              <v-card
                class="rounded-tl rounded-tr rounded-bl rounded-br elevation-1"
                color="white"
                flat
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      {{ stats.users_count.new_professionals_count }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text">New Professionals </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total number of Professionals that have joined between the dates selected above  </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>

            <v-col cols="6">
              <v-card
                class="
                  rounded-tl rounded-tr rounded-bl rounded-br
                  elevation-1
                  mt-n4
                "
                color="white"
                flat
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      {{ stats.users_count.pending_professional_count }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text">Blocked Professionals </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total number of professionals that have been blocked by CP admin </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>

            <v-col cols="6">
              <v-card
                class="
                  rounded-tl rounded-tr rounded-bl rounded-br
                  elevation-1
                  mt-n4
                "
                color="white"
                flat
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      {{ stats.users_count.active_professional_count }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text">Active Professionals</span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total number of professionals who have verified their email addresses </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>
          </v-row>
        </base-material-card>
      </v-col>
      <!-- <v-col cols="6">
        <base-material-card color="primary">
          <template v-slot:heading>
            <div class="text-h3 font-weight-light">Revenue</div>
          </template>
          <vue-apex-charts
            width="100%"
            height="350"
            type="line"
            :options="requestsChart.options"
            :series="requestsChart.series"
          />
        </base-material-card>
      </v-col> -->
      <v-col cols="6" class="px-0">
        <base-material-card style="background-color: #f7f7f7">
          <template v-slot:heading>
            <div class="text-h3 font-weight-light">Requests</div>
          </template>
           <vue-apex-charts
            width="100%"
            height="350"
            type="pie"
            :options="requestsPieChart.options"
            :series="requestsPieChart.series"
          />
          <v-row>
            <v-col cols="6">
              <v-card
                class="rounded-tl rounded-tr rounded-bl rounded-br elevation-1"
                color="white"
                flat
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      {{ stats.bookings_count.pending_requests_count }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text">Pending Requests </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total number of requests that are yet to be accepted or declined by the professionals </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>

            <v-col cols="6">
              <v-card
                class="rounded-tl rounded-tr rounded-bl rounded-br elevation-1"
                color="white"
                flat
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      {{ stats.bookings_count.declined_requests_count }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text">Declined Requests</span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total number of requests that have been declined by a professional  </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>

            <v-col cols="6">
              <v-card
                class="
                  rounded-tl rounded-tr rounded-bl rounded-br
                  elevation-1
                  mt-n4
                "
                color="white"
                flat
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      {{ stats.bookings_count.approved_requests_count }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text">Active Requests </span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total number of requests accepted by the professional </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>

            <v-col cols="6">
              <v-card
                class="
                  rounded-tl rounded-tr rounded-bl rounded-br
                  elevation-1
                  mt-n4
                "
                color="white"
                flat
              >
                <v-list-item>
                  <v-list-item-content class="pa-2">
                    <v-list-item-title class="text-h5 mb-1">
                      {{ stats.bookings_count.completed_requests_count }}
                      <br />
                      <v-list-item-subtitle>
                        <span class="black--text">Completed Requests</span>
                        <v-tooltip right>
                        <template v-slot:activator="{ on, attrs }">
                          <span>
                            <v-icon
                            small
                              v-bind="attrs"
                              v-on="on">
                              mdi-help-circle
                              </v-icon>
                          </span>
                          </template>
                          <span> Total number of requests that have been completed </span>
                          </v-tooltip>
                      </v-list-item-subtitle>
                    </v-list-item-title>
                  </v-list-item-content>
                </v-list-item>
              </v-card>
            </v-col>
          </v-row>
        </base-material-card>
      </v-col>

      <!-- <v-col cols="12">
        <base-material-card style="background-color: #f7f7f7">
          <template v-slot:heading>
            <div class="text-h3 font-weight-light">Bar Graph Last 7 Days</div>
          </template>
          <div>
            <div>
              <vue-apex-charts type="line"
                height="230"
                :options="chartOptionsArea"
                :series="series"></vue-apex-charts>
            </div>
            <div>
              <vue-apex-charts type="area"
                  height="130"
                  :options="chartOptionsBrush"
                  :series="series"></vue-apex-charts>
            </div>
          </div>
          
        
        </base-material-card>
      </v-col> -->
     
      <v-col cols="12" md="12">
        <h3 class="text-h3 font-weight-light text--primary">Recent Bookings</h3>
        <bookings class="px-0" :hide-default-footer="true" :max-rows="10" />
      </v-col>
      <v-col cols="12" md="12">
        <h3 class="text-h3 font-weight-light text--primary">KPI Stats</h3>
        <kpi-stats class="px-0" :hide-default-footer="true"/>
      </v-col>
      <v-col cols="12" md="12">
        <h3 class="text-h3 font-weight-light text--primary">Partnership Stats</h3>
        <partnership-stats class="px-0" :hide-default-footer="true"/>
      </v-col>
    </v-row>
  </v-container>
</template>


<script>
import { http } from "@/services/http-common";
import Bookings from "@/components/bookings";
import VueApexCharts from "vue-apexcharts";
import DateFilter from "@/components/dateFilter";
import VueBarGraph from 'vue-bar-graph';
import kpiStats from '@/components/kpiStats'
import partnershipStats from '@/components/partnershipStats'
import singlePartnershipStats from '@/components/singlePartnershipStats'
import { getKpiStats } from '@/services/admin'



export default {
  name: "DashboardDashboard",
  components: {
    Bookings,
    VueApexCharts,
    DateFilter,
    VueBarGraph,
    kpiStats,
    partnershipStats,
    singlePartnershipStats
  },

  data() {
    return {
      retain0 : 0,
      retain1 : 0,
      retain2 : 0,
      retain3 : 0,
      retain4 : 0,
      retain5 : 0,
      lineChartPoints: [],
      lineChart: false,
      // series: [
      //   {
      //     name: 'Revenue',
      //     data: [[122554002500, 30], [20320002250,20]]
      //   },
      //   {
      //     name: 'CP Commission',
      //     data: [[122554002500, 77], [20320002250,36]]
      //   },
      //   {
      //     name: 'Payouts',
      //     data: [[122554002500, 123], [20320002250,52]]
      //   }
      // ],
      // chartOptionsArea: {
      //   chart: {
      //     id: "chartArea",
      //     toolbar: {
      //       autoSelected: "pan",
      //       show: false
      //     }
      //   },
      //   colors: ["#546E7A"],
      //   stroke: {
      //     width: 1
      //   },
      //   dataLabels: {
      //     enabled: false
      //   },
      //   fill: {
      //     opacity: 1
      //   },
      //   markers: {
      //     size: 0
      //   },
      //   xaxis: {
      //     type: "datetime"
      //   }
      // },
      // chartOptionsBrush: {
      //   chart: {
      //     id: "chartBrush",
      //     brush: {
      //       target: "chartArea",
      //       enabled: true
      //     },
      //     selection: {
      //       enabled: true,
      //     }
      //   },
      //   colors: ["#008FFB"],
      //   fill: {
      //     gradient: {
      //       enabled: true,
      //       opacityFrom: 0.91,
      //       opacityTo: 0.1
      //     }
      //   },
      //   xaxis: {
      //     type: "datetime",
      //     tooltip: {
      //       enabled: false
      //     }
      //   },
      //   yaxis: {
      //     tickAmount: 3
      //   }
      // },

      usersChart: {
        options: {
          stroke: {
            curve: "smooth",
          },
          chart: {
            id: "users-charts",
          },
          xaxis: {
            categories: [],
            type: "datetime",
          },
          yaxis: [
            {
              title: {
                text: "Users",
              },
            },
          ],
        },
        series: [],
      },
      requestsChart: {
        options: {
          stroke: {
            curve: "smooth",
          },
          chart: {
            id: "users-charts",
          },
          xaxis: {
            categories: [],
            type: "datetime",
          },
          yaxis: [
            {
              title: {
                text: "Revenue",
              },
            },
          ],
        },
        series: [],
      },
      requestsPieChart: {
        options: {
          chart: {
            width: 380,
            type: "pie",
          },
          colors:['#F44336', '#E91E63', '#9C27B0','#F44336', '#E91E63', '#9C27B0'],
          labels: [
            // "Total Requests",
            "Completed ",
            "Cancelled ",
            "Expired ",
            "Approved ",
            "Declined ",
            "Pending ",
          ],
          responsive: [
            {
              breakpoint: 480,
              options: {
                chart: {
                  width: 200,
                },
                legend: {
                  position: "bottom",
                },
              },
            },
          ],
        },
        series: [],
      },
      stats: null,
      dateFilter: null,
      initDate: [],
      barGraphData: [],
      revenuePoints: [],
      commissionPoinnts: [],
      payoutPoints: [],
      bargraphKey: new Date(),
    };
  },
  computed: {
    // ...mapGetters(['stats']),
  },
  mounted() {
    const date = new Date();
    if (!localStorage.getItem("filterDate")) {
      this.initDate.push(`${date.getFullYear()}-${date.getMonth() + 1}-01`);
      this.initDate.push(
        `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}`
      );
    } else {
      let datearr = localStorage.getItem("filterDate").split(",");
      this.initDate.push(
        datearr[0]
      );
      this.initDate.push(
        datearr[1]
      );
    }
  },
  methods: {
    goToRetainCustomers(retain) {
      this.$router.push({ name: "Retain Customers", params: { retain: retain } });
    },
    toggleChart(){
      this.lineChart = !this.lineChart
      this.lineChartPoints=[]
      this.loadStats()
    },
    // constructBarGraphData(){
    //   this.series[0].data =this.generateDayWiseTimeSeries(this.barGraphData.revenue)
    //   this.series[1].data =this.generateDayWiseTimeSeries(this.barGraphData.cpCommision)
    //   this.series[2].data =this.generateDayWiseTimeSeries(this.barGraphData.withdrawl)
    // },
    graphDataIterator(revArray){
      let returningArray = []
      let today= String(new Date()).split(" ")[2]
      today = +today - 7
      let arrIndex = 0

      for(let i =0; i<7; i++){
        if(Number(revArray[arrIndex]?.date.split("-")[2]) == today){
          returningArray.push(revArray[arrIndex].total_amount)
          arrIndex++
          today++
        }else{
          returningArray.push(0)
          today++
        }
      }
      return returningArray
    },
    complete(index) {
      this.list[index] = !this.list[index];
    },
    toFixedTrunc(x, n) {
      const v = (typeof x === "string" ? x : x.toString()).split(".");
      if (n <= 0) return v[0];
      let f = v[1] || "";
      if (f.length > n) return `${v[0]}.${f.substr(0, n)}`;
      while (f.length < n) f += "0";
      return `${v[0]}.${f}`;
    },
    onDateChange(newValue) {
      if (newValue.length < 2) return;
      localStorage.setItem("filterDate", newValue);
      let finaldate = localStorage.getItem("filterDate").split(",");
      this.dateFilter = localStorage.getItem("filterDate")
        ? [new Date(finaldate[0]), new Date(finaldate[1])]
        : newValue;
      this.loadStats();
    },
    generateDayWiseTimeSeries(points) {
      let series= []
      points.map(rev=>{
        let date = new Date(rev.date)
        series.push([date.getTime(),Math.round(rev.total_amount)])
      })
      console.log('series', series);
      return
    },
    loadStats() {
      console.log(
        `${process.env.VUE_APP_API}/stats/?start=${this.dateFilter[0]}&end=${this.dateFilter[1]}`
      );
      http
        .get(
          `${process.env.VUE_APP_API}/stats/?start=${this.dateFilter[0]}&end=${this.dateFilter[1]}`
        )
        .then((res) => {
          this.stats = res.data;
          this.retain0 = this.stats.retain_users.retainedZeroth.totalCount+" ("+Math.round(this.stats.retain_users.retainedZeroth.percntage) +"%)"
          this.retain1 = this.stats.retain_users.retainedFirst.totalCount+" ("+Math.round(this.stats.retain_users.retainedFirst.percntage) +"%)"
          this.retain2 = this.stats.retain_users.retainedSecond.totalCount+" ("+Math.round(this.stats.retain_users.retainedSecond.percntage) +"%)"
          this.retain3 = this.stats.retain_users.retainedThird.totalCount+" ("+Math.round(this.stats.retain_users.retainedThird.percntage) +"%)"
          this.retain4 = this.stats.retain_users.retainedFourth.totalCount+" ("+Math.round(this.stats.retain_users.retainedFourth.percntage) +"%)"
          this.retain5 = this.stats.retain_users.retainedFifth.totalCount+" ("+Math.round(this.stats.retain_users.retainedFifth.percntage) +"%)"
          this.barGraphData = res.data.graphData
          // this.constructBarGraphData()
          this.usersChart.options.xaxis.categories = res.data.days;
          const usersDataPoints = [];
          const requestsDataPoints = [];
          const lastNumberOfCustomer =
            this.stats.users_count.total_customers -
            this.stats.users_count.new_customers_count;
          const lastNumberOfProfessional =
            this.stats.users_count.total_professional -
            this.stats.users_count.new_professionals_count;
          const lastTotalRevenue =
            this.stats.career_path_account_info.total_revenue -
            this.stats.career_path_account_info.total_revenue_new;
          const lastTotalDiscount =
            this.stats.career_path_account_info.total_discount -
            this.stats.career_path_account_info.total_discount_new;
          const lastTotalUnprocessed =
            this.stats.career_path_account_info.total_unprocessed -
            this.stats.career_path_account_info.total_unprocessed_new;
          const lastTotalCommisson =
            this.stats.career_path_account_info.total_commisson -
            this.stats.career_path_account_info.total_commission_new;
          const lastTotalProfessionalCommisson =
            this.stats.career_path_account_info.total_professional_commission -
            this.stats.career_path_account_info.total_professional_commission_new;
          const lastTotalPayout =
            this.stats.career_path_account_info.total_payouts -
            this.stats.career_path_account_info.total_payouts_new;
          const lastTotalRefund =
            this.stats.career_path_account_info.total_refund -
            this.stats.career_path_account_info.total_refund_new;

          this.stats.career_path_account_info.group_by_data.forEach((elm) => {
            if (elm.name === "Revenue") {
              let newRevenueArr = [];
              let total = 0;
              let total1 =0
              let newRevenueArr1 = []
              elm.count.map((row) => {
                total = total + parseFloat(row);
                total1= parseFloat(row);
                newRevenueArr1.push(total1.toFixed(2))
                newRevenueArr.push(total.toFixed(2));
              });
              requestsDataPoints.push({ name: elm.name, data: newRevenueArr });
              this.lineChartPoints.push({ name: elm.name, data: newRevenueArr1 });
            } else if (elm.name === "Unprocessed") {
              let newRevenueArr = [];
              let total = 0;
              let total1 =0
              let newRevenueArr1 = []
              elm.count.map((row) => {
                total = total + parseFloat(row);
                total1= parseFloat(row);
                newRevenueArr1.push(total1.toFixed(2))

                newRevenueArr.push(total.toFixed(2));
              });
              requestsDataPoints.push({ name: elm.name, data: newRevenueArr });
              this.lineChartPoints.push({ name: elm.name, data: newRevenueArr1 });
            } else if (elm.name === "Discounts") {
              let newRevenueArr = [];
              let total = 0;
              let total1 =0
              let newRevenueArr1 = []
              elm.count.map((row) => {
                total = total + parseFloat(row);
                total1= parseFloat(row);
                newRevenueArr1.push(total1.toFixed(2))

                newRevenueArr.push(total.toFixed(2));
              });
              requestsDataPoints.push({ name: elm.name, data: newRevenueArr });
              this.lineChartPoints.push({ name: elm.name, data: newRevenueArr1 });
            } else if (elm.name === "Commission") {
              let newRevenueArr = [];
              let total = 0;
              let total1 =0
              let newRevenueArr1 = []
              elm.count.map((row) => {
                total = total + parseFloat(row);
                total1= parseFloat(row);
                newRevenueArr1.push(total1.toFixed(2))
                newRevenueArr.push(total.toFixed(2));
              });
              requestsDataPoints.push({ name: elm.name, data: newRevenueArr });
              this.lineChartPoints.push({ name: elm.name, data: newRevenueArr1 });
            } else if (elm.name === "Payouts") {
              let newRevenueArr = [];
              let total = 0;
              let total1 =0
              let newRevenueArr1 = []
              elm.count.map((row) => {
                total = total + parseFloat(row);
                total1= parseFloat(row);
                newRevenueArr1.push(total1.toFixed(2))
                newRevenueArr.push(total.toFixed(2));
              });
              requestsDataPoints.push({ name: elm.name, data: newRevenueArr });
              this.lineChartPoints.push({ name: elm.name, data: newRevenueArr1 });
            } else {
              let newRevenueArr = [];
              let total = 0;
              let total1 =0
              let newRevenueArr1 = []
              elm.count.map((row) => {
                total = total + parseFloat(row);
                total1= parseFloat(row);
                newRevenueArr1.push(total1.toFixed(2))
                newRevenueArr.push(total.toFixed(2));
              });
              requestsDataPoints.push({ name: elm.name, data: newRevenueArr });
              this.lineChartPoints.push({ name: elm.name, data: newRevenueArr1 });
            }
          });
          const bookingsSeriesPieCart = [
            // this.stats.bookings_count.total_requests_count,
            this.stats.bookings_count.completed_requests_count,
            this.stats.bookings_count.cancelled_requests_count,
            this.stats.bookings_count.expired_requests_count,
            this.stats.bookings_count.approved_requests_count,
            this.stats.bookings_count.declined_requests_count,
            this.stats.bookings_count.pending_requests_count,
          ];
          console.log("pie", bookingsSeriesPieCart);
          this.stats.users_count.group_by_data.forEach((elm) => {
            if (elm.name === "Customers") {
              let newArr = [];
              let total = 0;
              elm.count.map((row) => {
                total += row;
                newArr.push(total);
              });
              usersDataPoints.push({ name: elm.name, data: newArr });
            } else {
              let newArr = [];
              let total = 0;
              elm.count.map((row) => {
                total += row;
                newArr.push(total);
              });
              usersDataPoints.push({ name: elm.name, data: newArr });
            }
          });
          this.usersChart.series = usersDataPoints;
          this.usersChart = {
            options: {
              stroke: {
                curve: "smooth",
              },
              chart: {
                id: "users-charts",
              },
              xaxis: {
                categories: res.data.days,
                type: "datetime",
              },
              yaxis: [
                {
                  title: {
                    text: "Users",
                  },
                },
              ],
              tooltip: {
    custom: function({ series, seriesIndex, dataPointIndex, w }) {
      console.log(series,"series")
      console.log(seriesIndex,"seriesIndex")
      console.log(dataPointIndex,"dataPointIndex")
      console.log( w.globals.seriesNames,"w")

      return (
        `
  <div class="container">
  <div class="items">
    <div class="items-head">
    </div>
    <div class="items-body">
      <div class="items-body-content">
        <li><span>${w.globals.seriesNames[0]} : ${series[0][dataPointIndex]}</span></li> 
      </div>
      <div class="items-body-content">
        <li><span>${w.globals.seriesNames[1]} : ${series[1][dataPointIndex]}</span></li>
      </div>
      <div class="items-body-content">
        <li><span>Ratio : ${(series[0][dataPointIndex] / series[1][dataPointIndex]).toFixed(2)}</span></li>
      </div>
    </div>
  </div>
</div>
` 
        
      );
    }
  }
            },
            series: usersDataPoints,
            
          };

          this.requestsChart = {
            options: {
              colors:['#73777B',  '#2d6a4f', '#990099', '#eeef20', '#5800FF', '#ff8fa3', '#171717', '#EB1D36'],
              stroke: {
                curve: "smooth",
              },
              chart: {
                id: "requests-charts",
                labels: {
                  formatter: function (value) {
                    return value + "£";
                  },
                },
              },
              xaxis: {
                categories: res.data.days,
                type: "datetime",
              },
              yaxis: [
                {
                  title: {
                    text: "£",
                    style: {
                      fontSize: '18px',
                      fontWeight: 'bold',
                    }
                  },
                },
              ],
            },
            series: this.lineChart? this.lineChartPoints : requestsDataPoints,
            tickAmount: 6,
          };
          this.requestsPieChart = {
            options: {
              chart: {
                width: 380,
                type: "pie",
              },
              colors:['#BA68C8', '#F06292', '#64B5F6','#81C784', '#FFD54F', '#FF8A65'],
              labels: [
                // "Total Requests",
                "Completed ",
                "Cancelled ",
                "Expired ",
                "Approved ",
                "Declined ",
                "Pending ",
              ],
              responsive: [
                {
                  breakpoint: 480,
                  options: {
                    chart: {
                      width: 200,
                    },
                    legend: {
                      position: "bottom",
                    },
                  },
                },
              ],
            },
            series: bookingsSeriesPieCart,
          };
        });
    },
  },
};
</script>
